### PR TITLE
RTE-Change-validations Correct validations

### PR DESCRIPTION
**Pull request by rntdrts**
Hi Jerry,

First of all thank's for the plugin, we been using it without any kind of problems and is helping us being very productive on multiple platforms. We had just a small throw back when we want to a ReactTouchEvents component to have only one event, the swipe.

I solved that this way, but I see other forms of resolve this if you want me to change the solution just say.

Cheers,
Renato Duarte.

### CODE REVIEW

**Comment by jerrybendy** [comment]
Hi @rntdrts ,

Thanks for your PR. I'm sorry for my poor English and I can't understand you better 😖.

I had browsed your code in PR. There has nothing real changes but format. 

Your said " _We had just a small throw back when we want to a ReactTouchEvents component to have only one event, the swipe_", do you mean remove `onTap` event ?

**Comment by rntdrts** [comment]
Hi @jerrybendy,

sorry for taking this long to answer your comment. My English could also be better, so I think the best way for us to understand each other is by using an example:

https://jsfiddle.net/rntdrt/z0g8ty4f/5/

You have to try it with mobile view and you will see that one click triggers the swipe event. I don't think that's the supposed behaviour. But you tell me :)

Thanks :)

**Comment by jerrybendy** [comment]
Hi @rntdrts ,

I have tried you example, and make sure the bug you said really exists. And your  code can resolve this bug, too. Thank you very much :+1:

**Comment by jerrybendy** [comment]
@rntdrts  Your code has already merged and published on npm. 
You can use `react-touch-events@^1.0.4` now.  :grin:

**Comment by rntdrts** [comment]
Thanks @jerrybendy :)

**Comment by jerrybendy** [comment]
You are welcome 😜

**Pull request merged**
